#!/usr/bin/env bash
# Post-training: merge LoRA, export to GGUF, build the Ollama image.
#
# Run AFTER notebooks/finetune_gemma_4_mycelium.ipynb has saved a LoRA at
# ./lora-gemma-4-mycelium-e4b/ and pushed merged GGUFs to the same dir.
#
# Requires: ollama (running), and the GGUF file produced by the notebook's
# llama.cpp quantize step.
#
# Usage:
#   ./scripts/export_to_ollama.sh [GGUF_PATH]
#
# Default GGUF path: ./lora-gemma-4-mycelium-e4b/gemma-4-mycelium-e4b-q4_k_m.gguf

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# Default matches the path scripts/finetune_lora.py emits in cell #9.
DEFAULT_GGUF="${REPO_ROOT}/gemma-4-mycelium-e4b.gguf"
GGUF_PATH="${1:-$DEFAULT_GGUF}"
MODELFILE_DST="${REPO_ROOT}/modelfile/Modelfile.local"
OLLAMA_TAG="crowelogic/gemma-4-mycelium-e4b"

if [[ ! -f "$GGUF_PATH" ]]; then
    echo "GGUF not found at: $GGUF_PATH"
    echo "Train + quantize first (see notebooks/finetune_gemma_4_mycelium.ipynb)."
    exit 1
fi

if ! command -v ollama >/dev/null 2>&1; then
    echo "ollama not installed. brew install ollama (macOS) then retry."
    exit 1
fi

# Generate a local Modelfile that points at the just-built GGUF.
# We copy the prompt + params from modelfile/Modelfile but swap FROM.
echo "[1/3] Writing $MODELFILE_DST (FROM $GGUF_PATH)"
{
    echo "# Auto-generated by scripts/export_to_ollama.sh"
    echo "# Source GGUF: $GGUF_PATH"
    echo ""
    echo "FROM $GGUF_PATH"
    echo ""
    # Append everything after the FROM line in the canonical Modelfile.
    awk '/^PARAMETER|^SYSTEM|^LICENSE|^TEMPLATE/{flag=1} flag' \
        "${REPO_ROOT}/modelfile/Modelfile"
} > "$MODELFILE_DST"

echo "[2/3] Building Ollama image: $OLLAMA_TAG"
ollama create "$OLLAMA_TAG" -f "$MODELFILE_DST"

echo "[3/3] Smoke test:"
ollama run "$OLLAMA_TAG" "What are you and what can you help me with?" 2>&1 | head -15

echo ""
echo "Done. Try: crowe-mycelium chat"
