#!/usr/bin/env bash
# Bridge: MLX-fused safetensors directory → Ollama image.
#
# `mlx_lm fuse` produces an HF-compatible safetensors directory (config.json
# + tokenizer.json + model-*.safetensors). Ollama's `ollama create` accepts
# this shape directly via `FROM <directory>` — no llama.cpp conversion step
# needed. This script wraps that path so the post-training pipeline is one
# command.
#
# If you prefer the GGUF route (smaller image, slightly different quantization
# behavior), pass `--gguf` and the script will invoke llama.cpp's
# convert_hf_to_gguf.py first, then hand off to scripts/export_to_ollama.sh.
#
# Usage:
#     ./scripts/mlx_to_ollama.sh                           # default: safetensors path
#     ./scripts/mlx_to_ollama.sh --gguf                    # convert via llama.cpp first
#     ./scripts/mlx_to_ollama.sh --merged ./path/to/dir    # custom merged dir
#     ./scripts/mlx_to_ollama.sh --tag user/name:tag       # custom Ollama tag
#
# Prerequisites:
#     1. Training complete (adapters/gemma-4-mycelium-e4b/ has adapters.safetensors)
#     2. `python scripts/finetune_lora_mlx.py fuse` run successfully (merged-*/
#        directory exists)
#     3. Ollama running

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

MERGED_DIR="${REPO_ROOT}/merged-gemma-4-mycelium-e4b"
OLLAMA_TAG="crowelogic/gemma-4-mycelium-e4b"
USE_GGUF=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --gguf)    USE_GGUF=1; shift ;;
        --merged)  MERGED_DIR="$2"; shift 2 ;;
        --tag)     OLLAMA_TAG="$2"; shift 2 ;;
        -h|--help)
            sed -n '2,/^$/p' "$0" | sed 's/^# //; s/^#//'
            exit 0
            ;;
        *) echo "unknown arg: $1"; exit 2 ;;
    esac
done

# ── 1. Verify merged dir exists + looks right ────────────────────────────

if [[ ! -d "$MERGED_DIR" ]]; then
    echo "Merged model directory not found: $MERGED_DIR"
    echo ""
    echo "Run the fuse step first:"
    echo "    python scripts/finetune_lora_mlx.py fuse"
    exit 1
fi

required_files=(config.json tokenizer.json tokenizer_config.json)
for f in "${required_files[@]}"; do
    if [[ ! -f "$MERGED_DIR/$f" ]]; then
        echo "  WARN: $MERGED_DIR/$f missing — fuse step may be incomplete"
    fi
done

shard_count=$(find "$MERGED_DIR" -maxdepth 1 -name "*.safetensors" 2>/dev/null | wc -l | tr -d ' ')
if [[ "$shard_count" = "0" ]]; then
    echo "ERROR: no *.safetensors files found in $MERGED_DIR"
    echo "       fuse step did not produce weight shards."
    exit 1
fi
echo "[1/4] merged dir OK ($shard_count safetensors shard(s) in $MERGED_DIR)"

# ── 2. Optional GGUF conversion (smaller image, llama.cpp dependency) ────

if [[ "$USE_GGUF" = "1" ]]; then
    GGUF_PATH="${REPO_ROOT}/gemma-4-mycelium-e4b.gguf"
    if [[ ! -f "$GGUF_PATH" ]]; then
        echo "[2/4] converting safetensors → GGUF via llama.cpp"
        if ! command -v convert_hf_to_gguf.py >/dev/null 2>&1; then
            # llama.cpp's convert script ships with the llama-cpp-python wheel.
            "${REPO_ROOT}/.venv/bin/pip" install -q llama-cpp-python
        fi
        "${REPO_ROOT}/.venv/bin/python" -m llama_cpp.convert_hf_to_gguf \
            "$MERGED_DIR" \
            --outfile "$GGUF_PATH" \
            --outtype q4_k_m
    else
        echo "[2/4] GGUF already exists at $GGUF_PATH (delete to rebuild)"
    fi
    # Hand off to the existing GGUF→Ollama path.
    exec "${REPO_ROOT}/scripts/export_to_ollama.sh" "$GGUF_PATH"
fi

# ── 3. Write a local Modelfile that points FROM the safetensors dir ──────

MODELFILE_LOCAL="${REPO_ROOT}/modelfile/Modelfile.local"
echo "[2/4] writing $MODELFILE_LOCAL (FROM $MERGED_DIR)"
{
    echo "# Auto-generated by scripts/mlx_to_ollama.sh"
    echo "# Source: $MERGED_DIR (MLX-fused safetensors)"
    echo "# Built:  $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo ""
    echo "FROM $MERGED_DIR"
    echo ""
    # Append PARAMETER/SYSTEM/TEMPLATE/LICENSE lines from the canonical
    # Modelfile so the merged weights inherit the cultivation system prompt
    # and sampling defaults.
    awk '/^PARAMETER|^SYSTEM|^LICENSE|^TEMPLATE/{flag=1} flag' \
        "${REPO_ROOT}/modelfile/Modelfile"
} > "$MODELFILE_LOCAL"

# ── 4. Build the Ollama image ─────────────────────────────────────────────

if ! command -v ollama >/dev/null 2>&1; then
    echo "ERROR: ollama not installed. brew install ollama, then retry."
    exit 1
fi

if ! pgrep -fq "ollama serve" 2>/dev/null; then
    echo "  starting Ollama daemon..."
    open -a Ollama 2>/dev/null || ollama serve &
    sleep 4
fi

echo "[3/4] building Ollama image: $OLLAMA_TAG"
echo "       (this converts safetensors → Ollama-internal blob format, takes ~30-60s)"
ollama create "$OLLAMA_TAG" -f "$MODELFILE_LOCAL"

echo "[4/4] smoke test"
ollama run "$OLLAMA_TAG" "Reply with exactly: PHASE2-LIVE" 2>&1 | tail -5

echo ""
echo "Phase 2 (fine-tuned) image built: $OLLAMA_TAG"
echo ""
echo "Next:"
echo "  Smoke-test cultivation behavior:"
echo "    ollama run $OLLAMA_TAG 'My agar plate has a pink patch on the side.'"
echo "  Push to Ollama Hub (needs SSH key linked to your account):"
echo "    ./scripts/setup_ollama_hub.sh push"
echo "  CLI:"
echo "    crowe-mycelium chat"
