# Commit any new shards in shards/ and push to GitHub.
# Idempotent: no-op if nothing changed.
$ErrorActionPreference = "Stop"

$repo = Split-Path -Parent $PSScriptRoot
Set-Location $repo

# Sanity: require remote configured
$remote = git config --get remote.origin.url
if (-not $remote) {
    Write-Error "No git remote 'origin' configured."
    exit 1
}

$status = git status --porcelain shards/
if (-not $status) {
    Write-Output "[shard] No changes in shards/. Nothing to push."
    exit 0
}

$shardCount = (Get-ChildItem $repo/shards/*.jsonl -ErrorAction SilentlyContinue).Count
$totalExamples = 0
$manifestPath = "$repo/shards/manifest.json"
if (Test-Path $manifestPath) {
    try {
        $manifest = Get-Content $manifestPath -Raw | ConvertFrom-Json
        $totalExamples = $manifest.total_examples
    } catch {}
}

$msg = "Add training shards: $shardCount files / $totalExamples examples`n`nGenerated by scripts/synth_magpie.py"

git add shards/
git commit -m $msg
git push origin HEAD
Write-Output "[shard] Pushed $shardCount shard(s) / $totalExamples examples."
